### ISSUE TITLE
Undefined method each for nil:NilClass (helpers.rb)

### ISSUE THREAD

**Issue by nater540** [gjtorikian/graphql-docs#20]
I have a rake task that attempts to generate documentation from an already built schema file:
```ruby
task :docs, [:schema_path, :output_path] => :environment do |t, args|
    args.with_defaults(schema_path: 'data/schema.json')
    args.with_defaults(output_path: 'docs')

    schema_path = Rails.root.join(args.schema_path)
    unless File.exist?(schema_path)
      puts 'Schema does not exist, generating...'
      Rake::Task['graphql:schema'].invoke(schema_path)
    end

    GraphQLDocs.build(path: schema_path, output_dir: args.output_path, base_url: '', delete_output: true)
  end
```

However it fails with the following error:
```shell
** Invoke graphql:docs (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute graphql:docs
rake aborted!
NoMethodError: undefined method `each' for nil:NilClass
(erb):112:in `block in include'
/usr/local/lib/ruby/2.4.0/erb.rb:896:in `eval'
/usr/local/lib/ruby/2.4.0/erb.rb:896:in `result'
/usr/local/bundle/gems/graphql-docs-0.5.2/lib/graphql-docs/helpers.rb:16:in `include'
(erb):30:in `call'
(erb):30:in `block in render'
/usr/local/lib/ruby/2.4.0/erb.rb:896:in `eval'
/usr/local/lib/ruby/2.4.0/erb.rb:896:in `result'
/usr/local/bundle/gems/graphql-docs-0.5.2/lib/graphql-docs/renderer.rb:49:in `render'
/usr/local/bundle/gems/graphql-docs-0.5.2/lib/graphql-docs/generator.rb:191:in `write_file'
/usr/local/bundle/gems/graphql-docs-0.5.2/lib/graphql-docs/generator.rb:109:in `block in create_graphql_object_pages'
/usr/local/bundle/gems/graphql-docs-0.5.2/lib/graphql-docs/generator.rb:83:in `each'
/usr/local/bundle/gems/graphql-docs-0.5.2/lib/graphql-docs/generator.rb:83:in `create_graphql_object_pages'
/usr/local/bundle/gems/graphql-docs-0.5.2/lib/graphql-docs/generator.rb:28:in `generate'
/usr/local/bundle/gems/graphql-docs-0.5.2/lib/graphql-docs.rb:39:in `build'
/doctor-finder/lib/tasks/graphql.rake:25:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/bundle/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:17:in `load'
/usr/local/bundle/bin/rake:17:in `<main>'
Tasks: TOP => graphql:docs
```

Here is the [schema file](https://pastebin.com/G6WgvGpM) if you would like to attempt to reproduce the error.

**Comment by gjtorikian** [comment]
Thanks very much for the schema file, that helps a lot!

I was able to find the error and will push a fix very shortly.
