### ISSUE TITLE
Legacy `.graphql_definition` objects are deprecated and will be removed in GraphQL-Ruby 2.0. Remove `.graphql_definition` to use a class-based definition instead.

### ISSUE THREAD

**Issue by niedfelj** [gjtorikian/graphql-docs#88]
Is this gem being maintained?

```
Called on #<GraphQL::Schema::NonNull @of_type=#<GraphQL::Schema::List:0x00007f78fdd6c4f0 @of_type=#<GraphQL::Schema::NonNull @of_type=#<Class:0x00007f78fdd6f8d0>>, @to_non_null_type=#<GraphQL::Schema::NonNull @of_type=#<GraphQL::Schema::List:0x00007f78fdd6c4f0 ...>>>> from:
   /Users/joel/.rvm/gems/ruby-3.0.3/gems/graphql-docs-2.0.1/lib/graphql-docs/parser.rb:220:in `generate_type'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/graphql-docs-2.0.1/lib/graphql-docs/parser.rb:170:in `block in fetch_fields'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/graphql-docs-2.0.1/lib/graphql-docs/parser.rb:159:in `each_value'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/graphql-docs-2.0.1/lib/graphql-docs/parser.rb:159:in `fetch_fields'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/graphql-docs-2.0.1/lib/graphql-docs/parser.rb:78:in `block in parse'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/graphql-docs-2.0.1/lib/graphql-docs/parser.rb:42:in `each_value'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/graphql-docs-2.0.1/lib/graphql-docs/parser.rb:42:in `parse'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/graphql-docs-2.0.1/lib/graphql-docs.rb:48:in `build'
  obfuscated.rake:7:in `block (2 levels) in <main>'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/railties-6.1.4.4/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /Users/joel/.rvm/gems/ruby-3.0.3/gems/railties-6.1.4.4/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
[master 78ac8f8] forcing year, should break tests
 1 file changed, 4 insertions(+), 1 deletion(-)

**Comment by gjtorikian** [comment]
Sure, and it takes pull requests too.

**Comment by alecslupu** [comment]
@gjtorikian I have added a fix, as i am also affected by this. Please feel free to review & merge.
